// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});




// // This is your Prisma schema file,
// // learn more about it in the docs: https://pris.ly/d/prisma-schema

// // Get a free hosted Postgres database in seconds: `npx create-db`

// generator client {
//   provider = "prisma-client"
//   output   = "../generated/prisma"
// }

// datasource db {
//   provider = "postgresql"
// }





// enum Role {
//   USER
//   ADMIN
// }

// enum LeadType {
//   INQUIRY
// }

// enum BookingStatus {
//   PENDING
//   CONFIRMED
//   COMPLETED
//   CANCELLED
// }

// //////////////////////////////////////////////////////
// // USER
// //////////////////////////////////////////////////////

// model User {
//   id        String   @id @default(uuid())
//   email     String   @unique
//   password  String
//   role      Role     @default(USER)
//   verified  Boolean  @default(false)

//   createdAt DateTime @default(now())
//   updatedAt DateTime @updatedAt

//   businessProfiles BusinessProfile[]
// }

// //////////////////////////////////////////////////////
// // BUSINESS (SALON)
// //////////////////////////////////////////////////////

// model BusinessProfile {
//   id               String   @id @default(uuid())
//   ownerName        String?
//   businessName     String?
//   businessAddress  String?
//   businessEmail    String?
//   businessContact  String?
//   description      String?

//   ownerId String
//   owner   User @relation(fields: [ownerId], references: [id])

//   createdAt DateTime @default(now())
//   updatedAt DateTime @updatedAt

//   categories Category[]
//   services   Service[]
//   packages   Package[]
//   leads      Lead[]
//   bookings   Booking[]
// }

// //////////////////////////////////////////////////////
// // CATEGORY (supports nesting)
// //////////////////////////////////////////////////////

// model Category {
//   id   String @id @default(uuid())
//   name String

//   parentId String?
//   parent   Category?  @relation("CategoryToCategory", fields: [parentId], references: [id])
//   children Category[] @relation("CategoryToCategory")

//   businessProfileId String
//   businessProfile   BusinessProfile @relation(fields: [businessProfileId], references: [id])

//   services Service[]
// }

// //////////////////////////////////////////////////////
// // SERVICE
// //////////////////////////////////////////////////////

// model Service {
//   id          String  @id @default(uuid())
//   name        String
//   description String?

//   categoryId String
//   category   Category @relation(fields: [categoryId], references: [id])

//   businessProfileId String
//   businessProfile   BusinessProfile @relation(fields: [businessProfileId], references: [id])

//   variants ServiceVariant[]

//   createdAt DateTime @default(now())
//   updatedAt DateTime @updatedAt

//   packageItems PackageItem[]

//   bookingItems BookingItem[]
// }

// //////////////////////////////////////////////////////
// // SERVICE VARIANTS (IMPORTANT)
// //////////////////////////////////////////////////////

// model ServiceVariant {
//   id    String @id @default(uuid())
//   name  String // e.g. "Shoulder Length", "Full Body", "Face"
//   price Int

//   duration Int? // in minutes

//   serviceId String
//   service   Service @relation(fields: [serviceId], references: [id])

//   createdAt DateTime @default(now())

//   bookingItems BookingItem[]
// }

// //////////////////////////////////////////////////////
// // PACKAGES (combo services)
// //////////////////////////////////////////////////////

// model Package {
//   id    String @id @default(uuid())
//   name  String
//   price Int

//   businessProfileId String
//   businessProfile   BusinessProfile @relation(fields: [businessProfileId], references: [id])

//   items PackageItem[]

//   createdAt DateTime @default(now())
// }

// model PackageItem {
//   id String @id @default(uuid())

//   packageId String
//   package   Package @relation(fields: [packageId], references: [id])

//   serviceId String
//   service   Service @relation(fields: [serviceId], references: [id])
// }

// //////////////////////////////////////////////////////
// // LEADS (ONLY INQUIRIES)
// //////////////////////////////////////////////////////

// model Lead {
//   id      String   @id @default(uuid())
//   name    String?
//   contact String?

//   message String?

//   type LeadType @default(INQUIRY)

//   businessProfileId String
//   businessProfile   BusinessProfile @relation(fields: [businessProfileId], references: [id])

//   createdAt DateTime @default(now())
// }

// //////////////////////////////////////////////////////
// // BOOKINGS (REAL APPOINTMENTS)
// //////////////////////////////////////////////////////

// model Booking {
//   id String @id @default(uuid())

//   customerName String
//   contact      String

//   date DateTime

//   status BookingStatus @default(PENDING)

//   businessProfileId String
//   businessProfile   BusinessProfile @relation(fields: [businessProfileId], references: [id])

//   items BookingItem[]

//   createdAt DateTime @default(now())
// }

// model BookingItem {
//   id String @id @default(uuid())

//   bookingId String
//   booking   Booking @relation(fields: [bookingId], references: [id])

//   serviceId String
//   service   Service @relation(fields: [serviceId], references: [id])

//   variantId String?
//   variant   ServiceVariant? @relation(fields: [variantId], references: [id])
// }